<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HospitalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hospitals = [
            // مستشفيات القاهرة
            [
                'id' => 1,
                'name' => 'مستشفى القصر العيني',
                'description' => 'مستشفى جامعي تعليمي رئيسي',
                'license_number' => 'CAIRO001',
                'type' => 'university',
                'address' => 'شارع القصر العيني، وسط القاهرة',
                'phone' => '0223654321',
                'hotline' => '123',
                'email' => 'info@kasralainy.edu.eg',
                'website' => 'www.kasralainy.edu.eg',
                'longitude' => 31.2357,
                'latitude' => 30.0444,
                'region_id' => 1
            ],
            [
                'id' => 2,
                'name' => 'مستشفى عين شمس التخصصي',
                'description' => 'مستشفى جامعي متخصص',
                'license_number' => 'CAIRO002',
                'type' => 'university',
                'address' => 'شارع العباسية، عين شمس',
                'phone' => '0224567890',
                'hotline' => '16123',
                'email' => 'hospital@asu.edu.eg',
                'website' => 'www.asu.edu.eg',
                'longitude' => 31.2854,
                'latitude' => 30.0734,
                'region_id' => 10
            ],
            [
                'id' => 3,
                'name' => 'مستشفى دار الفؤاد',
                'description' => 'مستشفى خاص متخصص في أمراض القلب',
                'license_number' => 'CAIRO003',
                'type' => 'private',
                'address' => 'طريق الإسماعيلية، مدينة نصر',
                'phone' => '0226789012',
                'hotline' => '19911',
                'email' => 'info@darelfouad.com',
                'website' => 'www.darelfouad.com',
                'longitude' => 31.3260,
                'latitude' => 30.0626,
                'region_id' => 2
            ],
            [
                'id' => 4,
                'name' => 'مستشفى الطوارئ أحمد ماهر',
                'description' => 'مستشفى حكومي للطوارئ',
                'license_number' => 'CAIRO004',
                'type' => 'governmental',
                'address' => 'شارع أحمد ماهر، السيدة زينب',
                'phone' => '0223456789',
                'hotline' => '122',
                'email' => 'ahmed.maher@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2398,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 5,
                'name' => 'مستشفى النصر للأطفال',
                'description' => 'مستشفى متخصص في طب الأطفال',
                'license_number' => 'CAIRO005',
                'type' => 'governmental',
                'address' => 'شارع عباس العقاد، مدينة نصر',
                'phone' => '0226543210',
                'hotline' => '16111',
                'email' => 'children@nasr.gov.eg',
                'website' => null,
                'longitude' => 31.3379,
                'latitude' => 30.0734,
                'region_id' => 2
            ],
            [
                'id' => 6,
                'name' => 'مستشفى السلام الدولي',
                'description' => 'مستشفى خاص متعدد التخصصات',
                'license_number' => 'CAIRO006',
                'type' => 'private',
                'address' => 'كورنيش النيل، المعادي',
                'phone' => '0225789123',
                'hotline' => '19199',
                'email' => 'info@alsalam-hospital.com',
                'website' => 'www.alsalam-hospital.com',
                'longitude' => 31.2622,
                'latitude' => 29.9601,
                'region_id' => 4
            ],
            [
                'id' => 7,
                'name' => 'مستشفى الجلاء للولادة',
                'description' => 'مستشفى حكومي متخصص في الولادة وأمراض النساء',
                'license_number' => 'CAIRO007',
                'type' => 'governmental',
                'address' => 'شارع كورنيش النيل، وسط القاهرة',
                'phone' => '0223567890',
                'hotline' => '15555',
                'email' => 'maternity@gelaa.gov.eg',
                'website' => null,
                'longitude' => 31.2419,
                'latitude' => 30.0515,
                'region_id' => 1
            ],
            [
                'id' => 8,
                'name' => 'مستشفى 57357',
                'description' => 'مستشفى خيري لعلاج سرطان الأطفال',
                'license_number' => 'CAIRO008',
                'type' => 'charity',
                'address' => 'شارع 26 يوليو، وسط القاهرة',
                'phone' => '0219357357',
                'hotline' => '19357',
                'email' => 'info@57357.org',
                'website' => 'www.57357.org',
                'longitude' => 31.2307,
                'latitude' => 30.0566,
                'region_id' => 1
            ],

            // مستشفيات الجيزة
            [
                'id' => 9,
                'name' => 'مستشفى الجيزة العام',
                'description' => 'مستشفى حكومي رئيسي',
                'license_number' => 'GIZA001',
                'type' => 'governmental',
                'address' => 'شارع الجيزة، وسط الجيزة',
                'phone' => '0237654321',
                'hotline' => '122',
                'email' => 'giza.hospital@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2118,
                'latitude' => 30.0131,
                'region_id' => 11
            ],
            [
                'id' => 10,
                'name' => 'مستشفى دار الشفاء',
                'description' => 'مستشفى خاص متعدد التخصصات',
                'license_number' => 'GIZA002',
                'type' => 'private',
                'address' => 'شارع المهندسين، الدقي',
                'phone' => '0237890123',
                'hotline' => '19777',
                'email' => 'info@darshefa.com',
                'website' => 'www.darshefa.com',
                'longitude' => 31.2001,
                'latitude' => 30.0626,
                'region_id' => 13
            ],
            [
                'id' => 11,
                'name' => 'مستشفى الهرم التخصصي',
                'description' => 'مستشفى حكومي متخصص',
                'license_number' => 'GIZA003',
                'type' => 'governmental',
                'address' => 'شارع الهرم، الهرم',
                'phone' => '0235567890',
                'hotline' => '16222',
                'email' => 'haram@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1342,
                'latitude' => 29.9792,
                'region_id' => 14
            ],
            [
                'id' => 12,
                'name' => 'مستشفى 6 أكتوبر المركزي',
                'description' => 'مستشفى حكومي حديث',
                'license_number' => 'GIZA004',
                'type' => 'governmental',
                'address' => 'المحور المركزي، 6 أكتوبر',
                'phone' => '0238901234',
                'hotline' => '16444',
                'email' => 'october@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.9391,
                'latitude' => 29.9097,
                'region_id' => 15
            ],

            // مستشفيات الإسكندرية
            [
                'id' => 13,
                'name' => 'مستشفى الإسكندرية الرئيسي',
                'description' => 'مستشفى حكومي رئيسي',
                'license_number' => 'ALEX001',
                'type' => 'governmental',
                'address' => 'شارع الحرية، المنشية',
                'phone' => '0334567890',
                'hotline' => '122',
                'email' => 'alex.main@mohp.gov.eg',
                'website' => null,
                'longitude' => 29.9097,
                'latitude' => 31.2001,
                'region_id' => 17
            ],
            [
                'id' => 14,
                'name' => 'مستشفى سموحة الطبي',
                'description' => 'مستشفى خاص متطور',
                'license_number' => 'ALEX002',
                'type' => 'private',
                'address' => 'شارع مصطفى كامل، سموحة',
                'phone' => '0336789012',
                'hotline' => '19666',
                'email' => 'info@smouha-medical.com',
                'website' => 'www.smouha-medical.com',
                'longitude' => 29.9369,
                'latitude' => 31.2156,
                'region_id' => 18
            ],
            [
                'id' => 15,
                'name' => 'مستشفى الجامعة الإسكندرية',
                'description' => 'مستشفى جامعي تعليمي',
                'license_number' => 'ALEX003',
                'type' => 'university',
                'address' => 'شارع الخرطوم، الأزاريطة',
                'phone' => '0335678901',
                'hotline' => '16333',
                'email' => 'hospital@alexu.edu.eg',
                'website' => 'www.alexu.edu.eg',
                'longitude' => 29.9097,
                'latitude' => 31.2156,
                'region_id' => 17
            ],

            // مستشفيات الدقهلية (المنصورة)
            [
                'id' => 16,
                'name' => 'مستشفى المنصورة الجامعي',
                'description' => 'مستشفى جامعي متميز',
                'license_number' => 'MANS001',
                'type' => 'university',
                'address' => 'شارع الجمهورية، المنصورة',
                'phone' => '0502345678',
                'hotline' => '16555',
                'email' => 'hospital@mans.edu.eg',
                'website' => 'www.mans.edu.eg',
                'longitude' => 31.3660,
                'latitude' => 31.0364,
                'region_id' => 23
            ],
            [
                'id' => 17,
                'name' => 'مستشفى المنصورة العام',
                'description' => 'مستشفى حكومي رئيسي',
                'license_number' => 'MANS002',
                'type' => 'governmental',
                'address' => 'شارع البحر، المنصورة',
                'phone' => '0504567890',
                'hotline' => '122',
                'email' => 'mansoura@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.3660,
                'latitude' => 31.0404,
                'region_id' => 23
            ],

            // مستشفيات البحر الأحمر (الغردقة)
            [
                'id' => 18,
                'name' => 'مستشفى الغردقة العام',
                'description' => 'مستشفى حكومي سياحي',
                'license_number' => 'HURG001',
                'type' => 'governmental',
                'address' => 'شارع النصر، الغردقة',
                'phone' => '0653456789',
                'hotline' => '122',
                'email' => 'hurghada@mohp.gov.eg',
                'website' => null,
                'longitude' => 33.8116,
                'latitude' => 27.2579,
                'region_id' => 26
            ],
            [
                'id' => 19,
                'name' => 'مستشفى النجدة الدولي',
                'description' => 'مستشفى خاص للسياحة العلاجية',
                'license_number' => 'HURG002',
                'type' => 'private',
                'address' => 'الأحياء، الغردقة',
                'phone' => '0657890123',
                'hotline' => '19888',
                'email' => 'info@nagda-hospital.com',
                'website' => 'www.nagda-hospital.com',
                'longitude' => 33.8176,
                'latitude' => 27.2639,
                'region_id' => 26
            ],

            // مستشفيات طنطا (الغربية)
            [
                'id' => 20,
                'name' => 'مستشفى طنطا الجامعي',
                'description' => 'مستشفى جامعي طبي',
                'license_number' => 'TANT001',
                'type' => 'university',
                'address' => 'شارع الجيش، طنطا',
                'phone' => '0403456789',
                'hotline' => '16777',
                'email' => 'hospital@tanta.edu.eg',
                'website' => 'www.tanta.edu.eg',
                'longitude' => 31.0004,
                'latitude' => 30.7865,
                'region_id' => 33
            ],
            [
                'id' => 21,
                'name' => 'مستشفى طنطا العام',
                'description' => 'مستشفى حكومي إقليمي',
                'license_number' => 'TANT002',
                'type' => 'governmental',
                'address' => 'ميدان الساعة، طنطا',
                'phone' => '0405678901',
                'hotline' => '122',
                'email' => 'tanta@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0027,
                'latitude' => 30.7908,
                'region_id' => 33
            ],

            // مستشفيات أسيوط
            [
                'id' => 22,
                'name' => 'مستشفى أسيوط الجامعي',
                'description' => 'مستشفى جامعي كبير لصعيد مصر',
                'license_number' => 'ASYU001',
                'type' => 'university',
                'address' => 'شارع الجامعة، أسيوط',
                'phone' => '0882345678',
                'hotline' => '16999',
                'email' => 'hospital@aun.edu.eg',
                'website' => 'www.aun.edu.eg',
                'longitude' => 31.1837,
                'latitude' => 27.1783,
                'region_id' => 47
            ],
            [
                'id' => 23,
                'name' => 'مستشفى أسيوط العام',
                'description' => 'مستشفى حكومي مركزي',
                'license_number' => 'ASYU002',
                'type' => 'governmental',
                'address' => 'شارع الثورة، أسيوط',
                'phone' => '0884567890',
                'hotline' => '122',
                'email' => 'assiut@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1889,
                'latitude' => 27.1809,
                'region_id' => 47
            ],

            // مستشفيات أسوان
            [
                'id' => 24,
                'name' => 'مستشفى أسوان الجامعي',
                'description' => 'مستشفى جامعي جنوبي',
                'license_number' => 'ASWA001',
                'type' => 'university',
                'address' => 'شارع أبطال التحرير، أسوان',
                'phone' => '0972345678',
                'hotline' => '16888',
                'email' => 'hospital@aswu.edu.eg',
                'website' => 'www.aswu.edu.eg',
                'longitude' => 32.8998,
                'latitude' => 24.0889,
                'region_id' => 45
            ],
            [
                'id' => 25,
                'name' => 'مستشفى أسوان العام',
                'description' => 'مستشفى حكومي رئيسي',
                'license_number' => 'ASWA002',
                'type' => 'governmental',
                'address' => 'كورنيش النيل، أسوان',
                'phone' => '0974567890',
                'hotline' => '122',
                'email' => 'aswan@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.8769,
                'latitude' => 24.0889,
                'region_id' => 45
            ],

            // مستشفيات شرم الشيخ (جنوب سيناء)
            [
                'id' => 26,
                'name' => 'مستشفى شرم الشيخ الدولي',
                'description' => 'مستشفى خاص سياحي',
                'license_number' => 'SHAR001',
                'type' => 'private',
                'address' => 'نعمة باي، شرم الشيخ',
                'phone' => '0693456789',
                'hotline' => '19333',
                'email' => 'info@sharm-international.com',
                'website' => 'www.sharm-international.com',
                'longitude' => 34.2999,
                'latitude' => 27.9158,
                'region_id' => 53
            ],
            [
                'id' => 27,
                'name' => 'مستشفى شرم الشيخ العام',
                'description' => 'مستشفى حكومي سياحي',
                'license_number' => 'SHAR002',
                'type' => 'governmental',
                'address' => 'حي النور، شرم الشيخ',
                'phone' => '0695678901',
                'hotline' => '122',
                'email' => 'sharm@mohp.gov.eg',
                'website' => null,
                'longitude' => 34.2885,
                'latitude' => 27.8963,
                'region_id' => 53
            ],

            // مستشفيات بورسعيد
            [
                'id' => 28,
                'name' => 'مستشفى بورسعيد العام',
                'description' => 'مستشفى حكومي بحري',
                'license_number' => 'PORT001',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، بورسعيد',
                'phone' => '0663456789',
                'hotline' => '122',
                'email' => 'portsaid@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.3019,
                'latitude' => 31.2653,
                'region_id' => 49
            ],

            // مستشفيات الإسماعيلية
            [
                'id' => 29,
                'name' => 'مستشفى الإسماعيلية العام',
                'description' => 'مستشفى حكومي القناة',
                'license_number' => 'ISMA001',
                'type' => 'governmental',
                'address' => 'شارع صلاح سالم، الإسماعيلية',
                'phone' => '0643456789',
                'hotline' => '122',
                'email' => 'ismailia@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.2668,
                'latitude' => 30.5965,
                'region_id' => 35
            ],

            // مستشفيات السويس
            [
                'id' => 30,
                'name' => 'مستشفى السويس العام',
                'description' => 'مستشفى حكومي بحري',
                'license_number' => 'SUEZ001',
                'type' => 'governmental',
                'address' => 'شارع الأربعين، السويس',
                'phone' => '0623456789',
                'hotline' => '122',
                'email' => 'suez@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.5498,
                'latitude' => 29.9668,
                'region_id' => 44
            ],

            // مزيد من مستشفيات القاهرة
            [
                'id' => 31,
                'name' => 'مستشفى المقطم للتأمين الصحي',
                'description' => 'مستشفى تأمين صحي',
                'license_number' => 'CAIRO009',
                'type' => 'governmental',
                'address' => 'شارع 9، المقطم',
                'phone' => '0228123456',
                'hotline' => '16555',
                'email' => 'mokattam@hio.gov.eg',
                'website' => null,
                'longitude' => 31.2844,
                'latitude' => 30.0081,
                'region_id' => 8
            ],
            [
                'id' => 32,
                'name' => 'مستشفى النزهة الدولي',
                'description' => 'مستشفى خاص متطور',
                'license_number' => 'CAIRO010',
                'type' => 'private',
                'address' => 'شارع النزهة، مصر الجديدة',
                'phone' => '0226654321',
                'hotline' => '19456',
                'email' => 'info@nozha-hospital.com',
                'website' => 'www.nozha-hospital.com',
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],

            // مزيد من مستشفيات الجيزة
            [
                'id' => 33,
                'name' => 'مستشفى الشيخ زايد التخصصي',
                'description' => 'مستشفى خاص متطور',
                'license_number' => 'GIZA005',
                'type' => 'private',
                'address' => 'الحي السابع، الشيخ زايد',
                'phone' => '0238887777',
                'hotline' => '19123',
                'email' => 'info@szsh.com',
                'website' => 'www.szsh.com',
                'longitude' => 30.9743,
                'latitude' => 30.0982,
                'region_id' => 16
            ],

            // مزيد من مستشفيات الإسكندرية
            [
                'id' => 34,
                'name' => 'مستشفى برج العرب العام',
                'description' => 'مستشفى حكومي جديد',
                'license_number' => 'ALEX004',
                'type' => 'governmental',
                'address' => 'برج العرب الجديدة، الإسكندرية',
                'phone' => '0334556677',
                'hotline' => '122',
                'email' => 'borgalarab@mohp.gov.eg',
                'website' => null,
                'longitude' => 29.6333,
                'latitude' => 30.9167,
                'region_id' => 22
            ],

            // مستشفيات البحيرة
            [
                'id' => 35,
                'name' => 'مستشفى دمنهور العام',
                'description' => 'مستشفى حكومي إقليمي',
                'license_number' => 'BEHI001',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، دمنهور',
                'phone' => '0453456789',
                'hotline' => '122',
                'email' => 'damanhour@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.4732,
                'latitude' => 31.0364,
                'region_id' => 29
            ],

            // مستشفيات الفيوم
            [
                'id' => 36,
                'name' => 'مستشفى الفيوم العام',
                'description' => 'مستشفى حكومي رئيسي',
                'license_number' => 'FAYU001',
                'type' => 'governmental',
                'address' => 'شارع السواقي، الفيوم',
                'phone' => '0843456789',
                'hotline' => '122',
                'email' => 'fayoum@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.8418,
                'latitude' => 29.3084,
                'region_id' => 31
            ],

            // مزيد من مستشفيات الغربية
            [
                'id' => 37,
                'name' => 'مستشفى المحلة الكبرى العام',
                'description' => 'مستشفى حكومي صناعي',
                'license_number' => 'GHAR002',
                'type' => 'governmental',
                'address' => 'شارع بور سعيد، المحلة الكبرى',
                'phone' => '0402345678',
                'hotline' => '122',
                'email' => 'mahalla@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1667,
                'latitude' => 30.9667,
                'region_id' => 34
            ],

            // مستشفيات المنوفية
            [
                'id' => 38,
                'name' => 'مستشفى شبين الكوم العام',
                'description' => 'مستشفى حكومي محافظة',
                'license_number' => 'MENO001',
                'type' => 'governmental',
                'address' => 'شارع الجلاء، شبين الكوم',
                'phone' => '0483456789',
                'hotline' => '122',
                'email' => 'shebin@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0167,
                'latitude' => 30.5667,
                'region_id' => 36
            ],

            // مستشفيات المنيا
            [
                'id' => 39,
                'name' => 'مستشفى المنيا الجامعي',
                'description' => 'مستشفى جامعي إقليمي',
                'license_number' => 'MINY001',
                'type' => 'university',
                'address' => 'شارع كورنيش النيل، المنيا',
                'phone' => '0862345678',
                'hotline' => '16666',
                'email' => 'hospital@minia.edu.eg',
                'website' => 'www.minia.edu.eg',
                'longitude' => 30.7327,
                'latitude' => 28.0871,
                'region_id' => 38
            ],

            // مستشفيات القليوبية
            [
                'id' => 40,
                'name' => 'مستشفى بنها الجامعي',
                'description' => 'مستشفى جامعي تعليمي',
                'license_number' => 'QALY001',
                'type' => 'university',
                'address' => 'شارع الجامعة، بنها',
                'phone' => '0133456789',
                'hotline' => '16888',
                'email' => 'hospital@bu.edu.eg',
                'website' => 'www.bu.edu.eg',
                'longitude' => 31.1833,
                'latitude' => 30.4667,
                'region_id' => 40
            ],

            // مستشفيات بني سويف
            [
                'id' => 41,
                'name' => 'مستشفى بني سويف الجامعي',
                'description' => 'مستشفى جامعي حديث',
                'license_number' => 'BENI001',
                'type' => 'university',
                'address' => 'شارع صلاح سالم، بني سويف',
                'phone' => '0822345678',
                'hotline' => '16777',
                'email' => 'hospital@bsu.edu.eg',
                'website' => 'www.bsu.edu.eg',
                'longitude' => 31.0948,
                'latitude' => 29.0661,
                'region_id' => 48
            ],

            // مستشفيات دمياط
            [
                'id' => 42,
                'name' => 'مستشفى دمياط العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'DAMI001',
                'type' => 'governmental',
                'address' => 'شارع البحر، دمياط',
                'phone' => '0573456789',
                'hotline' => '122',
                'email' => 'damietta@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.8133,
                'latitude' => 31.4167,
                'region_id' => 50
            ],

            // مزيد من مستشفيات الشرقية
            [
                'id' => 43,
                'name' => 'مستشفى الزقازيق الجامعي',
                'description' => 'مستشفى جامعي رئيسي',
                'license_number' => 'SHAR003',
                'type' => 'university',
                'address' => 'شارع الجامعة، الزقازيق',
                'phone' => '0552345678',
                'hotline' => '16999',
                'email' => 'hospital@zu.edu.eg',
                'website' => 'www.zu.edu.eg',
                'longitude' => 31.5167,
                'latitude' => 30.5833,
                'region_id' => 51
            ],

            // مستشفيات كفر الشيخ
            [
                'id' => 44,
                'name' => 'مستشفى كفر الشيخ العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'KAFR001',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، كفر الشيخ',
                'phone' => '0473456789',
                'hotline' => '122',
                'email' => 'kafrsheikh@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1167,
                'latitude' => 31.1000,
                'region_id' => 55
            ],

            // مستشفيات مطروح
            [
                'id' => 45,
                'name' => 'مستشفى مرسى مطروح العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'MATR001',
                'type' => 'governmental',
                'address' => 'شارع الإسكندرية، مرسى مطروح',
                'phone' => '0463456789',
                'hotline' => '122',
                'email' => 'matrouh@mohp.gov.eg',
                'website' => null,
                'longitude' => 27.2373,
                'latitude' => 31.3543,
                'region_id' => 56
            ],

            // مستشفيات الأقصر
            [
                'id' => 46,
                'name' => 'مستشفى الأقصر الدولي',
                'description' => 'مستشفى خاص سياحي',
                'license_number' => 'LUXO001',
                'type' => 'private',
                'address' => 'شارع خالد بن الوليد، الأقصر',
                'phone' => '0952345678',
                'hotline' => '19777',
                'email' => 'info@luxor-international.com',
                'website' => 'www.luxor-international.com',
                'longitude' => 32.6396,
                'latitude' => 25.6872,
                'region_id' => 58
            ],

            // مستشفيات قنا
            [
                'id' => 47,
                'name' => 'مستشفى قنا الجامعي',
                'description' => 'مستشفى جامعي صعيدي',
                'license_number' => 'QENA001',
                'type' => 'university',
                'address' => 'شارع سوهاج، قنا',
                'phone' => '0962345678',
                'hotline' => '16888',
                'email' => 'hospital@svu.edu.eg',
                'website' => 'www.svu.edu.eg',
                'longitude' => 32.7167,
                'latitude' => 26.1500,
                'region_id' => 59
            ],

            // مستشفيات شمال سيناء
            [
                'id' => 48,
                'name' => 'مستشفى العريش العام',
                'description' => 'مستشفى حكومي حدودي',
                'license_number' => 'NSIN001',
                'type' => 'governmental',
                'address' => 'شارع الجلاء، العريش',
                'phone' => '0683456789',
                'hotline' => '122',
                'email' => 'arish@mohp.gov.eg',
                'website' => null,
                'longitude' => 33.8000,
                'latitude' => 31.1333,
                'region_id' => 60
            ],

            // مستشفيات سوهاج
            [
                'id' => 49,
                'name' => 'مستشفى سوهاج الجامعي',
                'description' => 'مستشفى جامعي صعيدي',
                'license_number' => 'SOHA001',
                'type' => 'university',
                'address' => 'شارع الكورنيش، سوهاج',
                'phone' => '0932345678',
                'hotline' => '16777',
                'email' => 'hospital@sohag-univ.edu.eg',
                'website' => 'www.sohag-univ.edu.eg',
                'longitude' => 31.6948,
                'latitude' => 26.5569,
                'region_id' => 61
            ],

            // مستشفى الوادي الجديد
            [
                'id' => 50,
                'name' => 'مستشفى الخارجة العام',
                'description' => 'مستشفى حكومي صحراوي',
                'license_number' => 'NEWV001',
                'type' => 'governmental',
                'address' => 'شارع الثورة، الخارجة',
                'phone' => '0923456789',
                'hotline' => '122',
                'email' => 'kharga@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.5431,
                'latitude' => 25.4510,
                'region_id' => 43
            ],

            // مزيد من مستشفيات القاهرة
            [
                'id' => 51,
                'name' => 'مستشفى الدمرداش',
                'description' => 'مستشفى جامعي تابع لعين شمس',
                'license_number' => 'CAIRO014',
                'type' => 'university',
                'address' => 'شارع الدمرداش، عباسية',
                'phone' => '0224051000',
                'hotline' => '16123',
                'email' => 'demerdash@med.asu.edu.eg',
                'website' => null,
                'longitude' => 31.2854,
                'latitude' => 30.0734,
                'region_id' => 10
            ],
            [
                'id' => 52,
                'name' => 'مستشفى المنيرة العام',
                'description' => 'مستشفى حكومي تخصصي',
                'license_number' => 'CAIRO015',
                'type' => 'governmental',
                'address' => 'شارع المنيرة، السيدة زينب',
                'phone' => '0223651200',
                'hotline' => '122',
                'email' => 'mouneera@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2298,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 53,
                'name' => 'مستشفى الفجالة',
                'description' => 'مستشفى حكومي مركزي',
                'license_number' => 'CAIRO016',
                'type' => 'governmental',
                'address' => 'شارع رمسيس، الفجالة',
                'phone' => '0225951000',
                'hotline' => '122',
                'email' => 'fagala@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2500,
                'latitude' => 30.0626,
                'region_id' => 1
            ],
            [
                'id' => 54,
                'name' => 'مستشفى الصدر بالعباسية',
                'description' => 'مستشفى متخصص في أمراض الصدر',
                'license_number' => 'CAIRO017',
                'type' => 'governmental',
                'address' => 'شارع العباسية، عباسية',
                'phone' => '0224832000',
                'hotline' => '15333',
                'email' => 'chest@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2854,
                'latitude' => 30.0734,
                'region_id' => 10
            ],
            [
                'id' => 55,
                'name' => 'مستشفى الحميات بالعباسية',
                'description' => 'مستشفى الأمراض المعدية',
                'license_number' => 'CAIRO018',
                'type' => 'governmental',
                'address' => 'شارع العباسية، عباسية',
                'phone' => '0224834000',
                'hotline' => '105',
                'email' => 'fever@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2854,
                'latitude' => 30.0734,
                'region_id' => 10
            ],
            [
                'id' => 56,
                'name' => 'مستشفى العبور',
                'description' => 'مستشفى حكومي حديث',
                'license_number' => 'CAIRO019',
                'type' => 'governmental',
                'address' => 'مدينة العبور، القاهرة',
                'phone' => '0244800000',
                'hotline' => '122',
                'email' => 'obour@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.4667,
                'latitude' => 30.2167,
                'region_id' => 7
            ],
            [
                'id' => 57,
                'name' => 'مستشفى الجراحة التخصصي',
                'description' => 'مستشفى متخصص في الجراحة',
                'license_number' => 'CAIRO020',
                'type' => 'governmental',
                'address' => 'شارع المنيل، المنيل',
                'phone' => '0223642000',
                'hotline' => '16789',
                'email' => 'surgery@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2298,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 58,
                'name' => 'مستشفى القلب بالدقي',
                'description' => 'مستشفى متخصص في جراحة القلب',
                'license_number' => 'CAIRO021',
                'type' => 'governmental',
                'address' => 'شارع التحرير، الدقي',
                'phone' => '0237614000',
                'hotline' => '16456',
                'email' => 'heart@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2001,
                'latitude' => 30.0626,
                'region_id' => 13
            ],
            [
                'id' => 59,
                'name' => 'مستشفى الطب النفسي',
                'description' => 'مستشفى متخصص في الطب النفسي',
                'license_number' => 'CAIRO022',
                'type' => 'governmental',
                'address' => 'شارع المنيل، المنيل',
                'phone' => '0223642500',
                'hotline' => '16777',
                'email' => 'psychiatry@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2298,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 60,
                'name' => 'مستشفى العيون بالجيزة',
                'description' => 'مستشفى متخصص في طب العيون',
                'license_number' => 'CAIRO023',
                'type' => 'governmental',
                'address' => 'شارع الجيزة، الجيزة',
                'phone' => '0237654321',
                'hotline' => '16888',
                'email' => 'eye@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2118,
                'latitude' => 30.0131,
                'region_id' => 11
            ],

            // مستشفيات خاصة في القاهرة الكبرى
            [
                'id' => 61,
                'name' => 'مستشفى الطب الجديد',
                'description' => 'مستشفى خاص متعدد التخصصات',
                'license_number' => 'CAIRO024',
                'type' => 'private',
                'address' => 'شارع التسعين، التجمع الخامس',
                'phone' => '0226177000',
                'hotline' => '19555',
                'email' => 'info@ntmc.com.eg',
                'website' => 'www.ntmc.com.eg',
                'longitude' => 31.4292,
                'latitude' => 30.0131,
                'region_id' => 7
            ],
            [
                'id' => 62,
                'name' => 'مستشفى الشروق',
                'description' => 'مستشفى خاص حديث',
                'license_number' => 'CAIRO025',
                'type' => 'private',
                'address' => 'مدينة الشروق، القاهرة',
                'phone' => '0244502000',
                'hotline' => '19333',
                'email' => 'info@shorouk-hospital.com',
                'website' => 'www.shorouk-hospital.com',
                'longitude' => 31.6167,
                'latitude' => 30.1167,
                'region_id' => 7
            ],
            [
                'id' => 63,
                'name' => 'مستشفى المركز الطبي الدولي',
                'description' => 'مستشفى خاص راقي',
                'license_number' => 'CAIRO026',
                'type' => 'private',
                'address' => 'شارع الثورة، مصر الجديدة',
                'phone' => '0224171000',
                'hotline' => '19199',
                'email' => 'info@imc-cairo.com',
                'website' => 'www.imc-cairo.com',
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],
            [
                'id' => 64,
                'name' => 'مستشفى كليوباترا',
                'description' => 'مستشفى خاص للنساء والولادة',
                'license_number' => 'CAIRO027',
                'type' => 'private',
                'address' => 'شارع التحرير، المهندسين',
                'phone' => '0237601000',
                'hotline' => '19777',
                'email' => 'info@cleopatra-hospital.com',
                'website' => 'www.cleopatra-hospital.com',
                'longitude' => 31.2001,
                'latitude' => 30.0626,
                'region_id' => 12
            ],
            [
                'id' => 65,
                'name' => 'مستشفى الزهراء',
                'description' => 'مستشفى خاص شامل',
                'license_number' => 'CAIRO028',
                'type' => 'private',
                'address' => 'شارع المعز، المعادي',
                'phone' => '0225261000',
                'hotline' => '19666',
                'email' => 'info@zahra-hospital.com',
                'website' => 'www.zahra-hospital.com',
                'longitude' => 31.2622,
                'latitude' => 29.9601,
                'region_id' => 4
            ],

            // مستشفيات عسكرية وشرطية
            [
                'id' => 66,
                'name' => 'المستشفى العسكري بكوبري القبة',
                'description' => 'مستشفى عسكري رئيسي',
                'license_number' => 'MILI001',
                'type' => 'military',
                'address' => 'كوبري القبة، القاهرة',
                'phone' => '0224516000',
                'hotline' => '14441',
                'email' => 'military@mod.gov.eg',
                'website' => null,
                'longitude' => 31.2854,
                'latitude' => 30.0890,
                'region_id' => 10
            ],
            [
                'id' => 67,
                'name' => 'مستشفى القوات الجوية',
                'description' => 'مستشفى عسكري للقوات الجوية',
                'license_number' => 'MILI002',
                'type' => 'military',
                'address' => 'مصر الجديدة، القاهرة',
                'phone' => '0224171500',
                'hotline' => '14442',
                'email' => 'airforce@mod.gov.eg',
                'website' => null,
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],
            [
                'id' => 68,
                'name' => 'مستشفى الشرطة',
                'description' => 'مستشفى تابع لوزارة الداخلية',
                'license_number' => 'POLI001',
                'type' => 'governmental',
                'address' => 'شارع الشيخ ريحان، عابدين',
                'phone' => '0223921000',
                'hotline' => '122',
                'email' => 'police@moi.gov.eg',
                'website' => null,
                'longitude' => 31.2500,
                'latitude' => 30.0444,
                'region_id' => 1
            ],

            // مزيد من مستشفيات الإسكندرية
            [
                'id' => 69,
                'name' => 'مستشفى الحضرة الجامعي',
                'description' => 'مستشفى جامعي تخصصي',
                'license_number' => 'ALEX007',
                'type' => 'university',
                'address' => 'شارع الحضرة، الإسكندرية',
                'phone' => '0334567891',
                'hotline' => '16444',
                'email' => 'hadra@alexu.edu.eg',
                'website' => 'www.alexu.edu.eg',
                'longitude' => 29.9369,
                'latitude' => 31.2156,
                'region_id' => 17
            ],
            [
                'id' => 70,
                'name' => 'مستشفى العجمي الخاص',
                'description' => 'مستشفى خاص ساحلي',
                'license_number' => 'ALEX008',
                'type' => 'private',
                'address' => 'كيلو 21، العجمي',
                'phone' => '0335567788',
                'hotline' => '19321',
                'email' => 'info@agami-hospital.com',
                'website' => 'www.agami-hospital.com',
                'longitude' => 29.8167,
                'latitude' => 31.1333,
                'region_id' => 21
            ],
            [
                'id' => 71,
                'name' => 'مستشفى المبرة',
                'description' => 'مستشفى خيري',
                'license_number' => 'ALEX009',
                'type' => 'charity',
                'address' => 'شارع أحمد شوقي، الإسكندرية',
                'phone' => '0334562000',
                'hotline' => '16000',
                'email' => 'mabarra@mabarra.org',
                'website' => 'www.mabarra.org',
                'longitude' => 29.9097,
                'latitude' => 31.2001,
                'region_id' => 17
            ],
            [
                'id' => 72,
                'name' => 'مستشفى الأطفال الجامعي',
                'description' => 'مستشفى جامعي للأطفال',
                'license_number' => 'ALEX010',
                'type' => 'university',
                'address' => 'شارع الحرية، الإسكندرية',
                'phone' => '0334512000',
                'hotline' => '16111',
                'email' => 'children@alexu.edu.eg',
                'website' => 'www.alexu.edu.eg',
                'longitude' => 29.9097,
                'latitude' => 31.2001,
                'region_id' => 17
            ],
            [
                'id' => 73,
                'name' => 'مستشفى النساء والتوليد الجامعي',
                'description' => 'مستشفى جامعي للنساء والولادة',
                'license_number' => 'ALEX011',
                'type' => 'university',
                'address' => 'شارع شامبليون، الإسكندرية',
                'phone' => '0334513000',
                'hotline' => '16222',
                'email' => 'obs-gyn@alexu.edu.eg',
                'website' => 'www.alexu.edu.eg',
                'longitude' => 29.9097,
                'latitude' => 31.2001,
                'region_id' => 17
            ],

            // مستشفيات الدقهلية (المنصورة وطلخا وميت غمر)
            [
                'id' => 74,
                'name' => 'مستشفى طلخا المركزي',
                'description' => 'مستشفى حكومي مركزي',
                'license_number' => 'MANS003',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، طلخا',
                'phone' => '0502456789',
                'hotline' => '122',
                'email' => 'talkha@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.3793,
                'latitude' => 31.0539,
                'region_id' => 24
            ],
            [
                'id' => 75,
                'name' => 'مستشفى ميت غمر العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MANS004',
                'type' => 'governmental',
                'address' => 'شارع الشهداء، ميت غمر',
                'phone' => '0503456789',
                'hotline' => '122',
                'email' => 'meetghamr@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2593,
                'latitude' => 30.7093,
                'region_id' => 25
            ],
            [
                'id' => 76,
                'name' => 'مستشفى شربين العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MANS005',
                'type' => 'governmental',
                'address' => 'شارع المحطة، شربين',
                'phone' => '0501456789',
                'hotline' => '122',
                'email' => 'sherbin@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.5167,
                'latitude' => 31.2000,
                'region_id' => 23
            ],
            [
                'id' => 77,
                'name' => 'مستشفى دكرنس العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'MANS006',
                'type' => 'governmental',
                'address' => 'شارع الزراعة، دكرنس',
                'phone' => '0504567890',
                'hotline' => '122',
                'email' => 'dekernes@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.4000,
                'latitude' => 30.9500,
                'region_id' => 23
            ],

            // مستشفيات البحيرة
            [
                'id' => 78,
                'name' => 'مستشفى كفر الدوار العام',
                'description' => 'مستشفى حكومي صناعي',
                'license_number' => 'BEHI003',
                'type' => 'governmental',
                'address' => 'شارع المحطة، كفر الدوار',
                'phone' => '0454567890',
                'hotline' => '122',
                'email' => 'kafrdawar@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.1333,
                'latitude' => 31.1333,
                'region_id' => 30
            ],
            [
                'id' => 79,
                'name' => 'مستشفى رشيد العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'BEHI004',
                'type' => 'governmental',
                'address' => 'شارع النيل، رشيد',
                'phone' => '0455678901',
                'hotline' => '122',
                'email' => 'rashid@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.4167,
                'latitude' => 31.4000,
                'region_id' => 29
            ],
            [
                'id' => 80,
                'name' => 'مستشفى إدكو العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'BEHI005',
                'type' => 'governmental',
                'address' => 'شارع البحيرة، إدكو',
                'phone' => '0456789012',
                'hotline' => '122',
                'email' => 'edko@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.3000,
                'latitude' => 31.3333,
                'region_id' => 29
            ],

            // مستشفيات الغربية
            [
                'id' => 81,
                'name' => 'مستشفى زفتى العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'GHAR004',
                'type' => 'governmental',
                'address' => 'شارع الشركة، زفتى',
                'phone' => '0405678901',
                'hotline' => '122',
                'email' => 'zefta@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2500,
                'latitude' => 30.7167,
                'region_id' => 33
            ],
            [
                'id' => 82,
                'name' => 'مستشفى السنطة العام',
                'description' => 'مستشفى حكومي زراعي',
                'license_number' => 'GHAR005',
                'type' => 'governmental',
                'address' => 'شارع المحطة، السنطة',
                'phone' => '0407890123',
                'hotline' => '122',
                'email' => 'santa@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0833,
                'latitude' => 30.8500,
                'region_id' => 33
            ],
            [
                'id' => 83,
                'name' => 'مستشفى بسيون العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'GHAR006',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، بسيون',
                'phone' => '0408901234',
                'hotline' => '122',
                'email' => 'basion@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0500,
                'latitude' => 30.9167,
                'region_id' => 33
            ],

            // مستشفيات المنوفية
            [
                'id' => 84,
                'name' => 'مستشفى منوف العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MENO003',
                'type' => 'governmental',
                'address' => 'شارع الشهداء، منوف',
                'phone' => '0485678901',
                'hotline' => '122',
                'email' => 'menouf@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.9333,
                'latitude' => 30.4667,
                'region_id' => 36
            ],
            [
                'id' => 85,
                'name' => 'مستشفى أشمون العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'MENO004',
                'type' => 'governmental',
                'address' => 'شارع النيل، أشمون',
                'phone' => '0486789012',
                'hotline' => '122',
                'email' => 'ashmon@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0167,
                'latitude' => 30.3167,
                'region_id' => 36
            ],
            [
                'id' => 86,
                'name' => 'مستشفى الباجور العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MENO005',
                'type' => 'governmental',
                'address' => 'شارع الثورة، الباجور',
                'phone' => '0487890123',
                'hotline' => '122',
                'email' => 'bagor@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0000,
                'latitude' => 30.4333,
                'region_id' => 36
            ],

            // مستشفيات المنيا
            [
                'id' => 87,
                'name' => 'مستشفى المنيا العام',
                'description' => 'مستشفى حكومي محافظة',
                'license_number' => 'MINY003',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، المنيا',
                'phone' => '0864567890',
                'hotline' => '122',
                'email' => 'minya@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.7444,
                'latitude' => 28.0996,
                'region_id' => 38
            ],
            [
                'id' => 88,
                'name' => 'مستشفى ملوي العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MINY004',
                'type' => 'governmental',
                'address' => 'شارع المحطة، ملوي',
                'phone' => '0863456789',
                'hotline' => '122',
                'email' => 'mallawi@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.8333,
                'latitude' => 27.7333,
                'region_id' => 39
            ],
            [
                'id' => 89,
                'name' => 'مستشفى بني مزار العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'MINY005',
                'type' => 'governmental',
                'address' => 'شارع النيل، بني مزار',
                'phone' => '0865678901',
                'hotline' => '122',
                'email' => 'benimazar@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.8167,
                'latitude' => 28.5000,
                'region_id' => 38
            ],
            [
                'id' => 90,
                'name' => 'مستشفى مغاغة العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'MINY006',
                'type' => 'governmental',
                'address' => 'شارع الجيش، مغاغة',
                'phone' => '0866789012',
                'hotline' => '122',
                'email' => 'maghagha@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.8333,
                'latitude' => 28.6500,
                'region_id' => 38
            ],

            // مستشفيات القليوبية
            [
                'id' => 91,
                'name' => 'مستشفى بنها العام',
                'description' => 'مستشفى حكومي محافظة',
                'license_number' => 'QALY004',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، بنها',
                'phone' => '0135678901',
                'hotline' => '122',
                'email' => 'benha@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1833,
                'latitude' => 30.4667,
                'region_id' => 40
            ],
            [
                'id' => 92,
                'name' => 'مستشفى الخانكة العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'QALY005',
                'type' => 'governmental',
                'address' => 'شارع السكة الحديد، الخانكة',
                'phone' => '0136789012',
                'hotline' => '122',
                'email' => 'khanka@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.3667,
                'latitude' => 30.2167,
                'region_id' => 40
            ],
            [
                'id' => 93,
                'name' => 'مستشفى طوخ العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'QALY006',
                'type' => 'governmental',
                'address' => 'شارع الزراعة، طوخ',
                'phone' => '0137890123',
                'hotline' => '122',
                'email' => 'tukh@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2000,
                'latitude' => 30.3833,
                'region_id' => 40
            ],

            // مستشفيات أسيوط
            [
                'id' => 94,
                'name' => 'مستشفى ديروط العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'ASYU003',
                'type' => 'governmental',
                'address' => 'شارع المحطة، ديروط',
                'phone' => '0886789012',
                'hotline' => '122',
                'email' => 'dairut@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.8000,
                'latitude' => 27.5500,
                'region_id' => 47
            ],
            [
                'id' => 95,
                'name' => 'مستشفى منفلوط العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'ASYU004',
                'type' => 'governmental',
                'address' => 'شارع النيل، منفلوط',
                'phone' => '0887890123',
                'hotline' => '122',
                'email' => 'manfalut@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.9667,
                'latitude' => 27.3167,
                'region_id' => 47
            ],
            [
                'id' => 96,
                'name' => 'مستشفى أبنوب العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'ASYU005',
                'type' => 'governmental',
                'address' => 'شارع الجيش، أبنوب',
                'phone' => '0888901234',
                'hotline' => '122',
                'email' => 'abnoub@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.1167,
                'latitude' => 27.2667,
                'region_id' => 47
            ],

            // مستشفيات بني سويف
            [
                'id' => 97,
                'name' => 'مستشفى الواسطى العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'BENI003',
                'type' => 'governmental',
                'address' => 'شارع النيل، الواسطى',
                'phone' => '0825678901',
                'hotline' => '122',
                'email' => 'wasta@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2000,
                'latitude' => 29.3333,
                'region_id' => 48
            ],
            [
                'id' => 98,
                'name' => 'مستشفى ناصر العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'BENI004',
                'type' => 'governmental',
                'address' => 'شارع الشهداء، ناصر',
                'phone' => '0826789012',
                'hotline' => '122',
                'email' => 'naser@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0833,
                'latitude' => 29.1167,
                'region_id' => 48
            ],
            [
                'id' => 99,
                'name' => 'مستشفى ببا العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'BENI005',
                'type' => 'governmental',
                'address' => 'شارع المحطة، ببا',
                'phone' => '0827890123',
                'hotline' => '122',
                'email' => 'beba@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2500,
                'latitude' => 29.2000,
                'region_id' => 48
            ],

            // مستشفيات الشرقية
            [
                'id' => 100,
                'name' => 'مستشفى أبو حماد العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'SHAR004',
                'type' => 'governmental',
                'address' => 'شارع البلدية، أبو حماد',
                'phone' => '0557890123',
                'hotline' => '122',
                'email' => 'abuhammad@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.7833,
                'latitude' => 30.7167,
                'region_id' => 51
            ],

            // مزيد من مستشفيات الشرقية
            [
                'id' => 101,
                'name' => 'مستشفى فاقوس العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'SHAR005',
                'type' => 'governmental',
                'address' => 'شارع المحطة، فاقوس',
                'phone' => '0558901234',
                'hotline' => '122',
                'email' => 'faqous@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.8000,
                'latitude' => 30.7500,
                'region_id' => 51
            ],
            [
                'id' => 102,
                'name' => 'مستشفى ديرب نجم العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'SHAR006',
                'type' => 'governmental',
                'address' => 'شارع النيل، ديرب نجم',
                'phone' => '0559012345',
                'hotline' => '122',
                'email' => 'dairbnagm@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.8667,
                'latitude' => 30.8167,
                'region_id' => 51
            ],
            [
                'id' => 103,
                'name' => 'مستشفى كفر صقر العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'SHAR007',
                'type' => 'governmental',
                'address' => 'شارع الحكومة، كفر صقر',
                'phone' => '0550123456',
                'hotline' => '122',
                'email' => 'kafrsaqr@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.6333,
                'latitude' => 30.7833,
                'region_id' => 51
            ],

            // مستشفيات كفر الشيخ
            [
                'id' => 104,
                'name' => 'مستشفى دسوق العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'KAFR004',
                'type' => 'governmental',
                'address' => 'شارع الجمهورية، دسوق',
                'phone' => '0473456789',
                'hotline' => '122',
                'email' => 'desouk@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.6333,
                'latitude' => 31.1333,
                'region_id' => 52
            ],
            [
                'id' => 105,
                'name' => 'مستشفى فوه العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'KAFR005',
                'type' => 'governmental',
                'address' => 'شارع البحر، فوه',
                'phone' => '0474567890',
                'hotline' => '122',
                'email' => 'fouh@mohp.gov.eg',
                'website' => null,
                'longitude' => 30.5500,
                'latitude' => 31.2833,
                'region_id' => 52
            ],
            [
                'id' => 106,
                'name' => 'مستشفى بلطيم العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'KAFR006',
                'type' => 'governmental',
                'address' => 'شارع الكورنيش، بلطيم',
                'phone' => '0475678901',
                'hotline' => '122',
                'email' => 'baltim@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.0500,
                'latitude' => 31.5500,
                'region_id' => 52
            ],

            // مستشفيات دمياط
            [
                'id' => 107,
                'name' => 'مستشفى فارسكور العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'DAMI003',
                'type' => 'governmental',
                'address' => 'شارع المحطة، فارسكور',
                'phone' => '0576789012',
                'hotline' => '122',
                'email' => 'faraskour@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.3333,
                'latitude' => 31.3333,
                'region_id' => 53
            ],
            [
                'id' => 108,
                'name' => 'مستشفى رأس البر السياحي',
                'description' => 'مستشفى حكومي سياحي',
                'license_number' => 'DAMI004',
                'type' => 'governmental',
                'address' => 'كورنيش النيل، رأس البر',
                'phone' => '0577890123',
                'hotline' => '122',
                'email' => 'rasalbar@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.5000,
                'latitude' => 31.5167,
                'region_id' => 53
            ],
            [
                'id' => 109,
                'name' => 'مستشفى الزرقا العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'DAMI005',
                'type' => 'governmental',
                'address' => 'شارع الزراعة، الزرقا',
                'phone' => '0578901234',
                'hotline' => '122',
                'email' => 'zarqa@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.6167,
                'latitude' => 31.2833,
                'region_id' => 53
            ],

            // مستشفيات بورسعيد
            [
                'id' => 110,
                'name' => 'مستشفى التضامن',
                'description' => 'مستشفى حكومي اجتماعي',
                'license_number' => 'PORT003',
                'type' => 'governmental',
                'address' => 'شارة التضامن، بورسعيد',
                'phone' => '0663456789',
                'hotline' => '122',
                'email' => 'tadamon@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.2876,
                'latitude' => 31.2653,
                'region_id' => 54
            ],
            [
                'id' => 111,
                'name' => 'مستشفى بورفؤاد العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'PORT004',
                'type' => 'governmental',
                'address' => 'شارع 23 يوليو، بورفؤاد',
                'phone' => '0664567890',
                'hotline' => '122',
                'email' => 'borfuad@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.3167,
                'latitude' => 31.2833,
                'region_id' => 54
            ],

            // مستشفيات الإسماعيلية
            [
                'id' => 112,
                'name' => 'مستشفى القنطرة العام',
                'description' => 'مستشفى حكومي استراتيجي',
                'license_number' => 'ISMA003',
                'type' => 'governmental',
                'address' => 'شارع القناة، القنطرة',
                'phone' => '0644567890',
                'hotline' => '122',
                'email' => 'qantara@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.3167,
                'latitude' => 30.8833,
                'region_id' => 55
            ],
            [
                'id' => 113,
                'name' => 'مستشفى أبو صوير العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'ISMA004',
                'type' => 'governmental',
                'address' => 'شارع المطار، أبو صوير',
                'phone' => '0645678901',
                'hotline' => '122',
                'email' => 'abusoir@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.1167,
                'latitude' => 30.7000,
                'region_id' => 55
            ],
            [
                'id' => 114,
                'name' => 'مستشفى فايد العام',
                'description' => 'مستشفى حكومي بحيري',
                'license_number' => 'ISMA005',
                'type' => 'governmental',
                'address' => 'شارع البحيرة، فايد',
                'phone' => '0646789012',
                'hotline' => '122',
                'email' => 'fayed@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.3000,
                'latitude' => 30.3167,
                'region_id' => 55
            ],

            // مستشفيات الأقصر
            [
                'id' => 115,
                'name' => 'مستشفى إسنا العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'LUXO003',
                'type' => 'governmental',
                'address' => 'شارع المعبد، إسنا',
                'phone' => '0957890123',
                'hotline' => '122',
                'email' => 'esna@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.5533,
                'latitude' => 25.2919,
                'region_id' => 56
            ],
            [
                'id' => 116,
                'name' => 'مستشفى أرمنت العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'LUXO004',
                'type' => 'governmental',
                'address' => 'شارع النيل، أرمنت',
                'phone' => '0958901234',
                'hotline' => '122',
                'email' => 'armant@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.5667,
                'latitude' => 25.6000,
                'region_id' => 56
            ],

            // مستشفيات قنا
            [
                'id' => 117,
                'name' => 'مستشفى قوص العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'QENA003',
                'type' => 'governmental',
                'address' => 'شارع الفراعنة، قوص',
                'phone' => '0967890123',
                'hotline' => '122',
                'email' => 'qous@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.7667,
                'latitude' => 25.9167,
                'region_id' => 57
            ],
            [
                'id' => 118,
                'name' => 'مستشفى نقادة العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'QENA004',
                'type' => 'governmental',
                'address' => 'شارع الشهداء، نقادة',
                'phone' => '0968901234',
                'hotline' => '122',
                'email' => 'naqada@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.7333,
                'latitude' => 25.9000,
                'region_id' => 57
            ],
            [
                'id' => 119,
                'name' => 'مستشفى فرشوط العام',
                'description' => 'مستشفى حكومي ريفي',
                'license_number' => 'QENA005',
                'type' => 'governmental',
                'address' => 'شارع الزراعة، فرشوط',
                'phone' => '0969012345',
                'hotline' => '122',
                'email' => 'farshout@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.8000,
                'latitude' => 26.0500,
                'region_id' => 57
            ],

            // مستشفيات أسوان
            [
                'id' => 120,
                'name' => 'مستشفى كوم أمبو العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'ASWA003',
                'type' => 'governmental',
                'address' => 'شارع المعبد، كوم أمبو',
                'phone' => '0975678901',
                'hotline' => '122',
                'email' => 'komambo@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.9333,
                'latitude' => 24.4667,
                'region_id' => 58
            ],
            [
                'id' => 121,
                'name' => 'مستشفى إدفو العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'ASWA004',
                'type' => 'governmental',
                'address' => 'شارع المعبد، إدفو',
                'phone' => '0976789012',
                'hotline' => '122',
                'email' => 'edfu@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.8733,
                'latitude' => 24.9781,
                'region_id' => 58
            ],
            [
                'id' => 122,
                'name' => 'مستشفى نصر النوبة',
                'description' => 'مستشفى حكومي نوبي',
                'license_number' => 'ASWA005',
                'type' => 'governmental',
                'address' => 'شارة النوبة، نصر النوبة',
                'phone' => '0977890123',
                'hotline' => '122',
                'email' => 'nasralnuba@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.8833,
                'latitude' => 22.9167,
                'region_id' => 58
            ],

            // مستشفيات الوادي الجديد
            [
                'id' => 123,
                'name' => 'مستشفى باريس العام',
                'description' => 'مستشفى حكومي واحة',
                'license_number' => 'VALL003',
                'type' => 'governmental',
                'address' => 'شارع الواحة، باريس',
                'phone' => '0926789012',
                'hotline' => '122',
                'email' => 'paris@mohp.gov.eg',
                'website' => null,
                'longitude' => 28.5500,
                'latitude' => 25.4000,
                'region_id' => 59
            ],
            [
                'id' => 124,
                'name' => 'مستشفى موط العام',
                'description' => 'مستشفى حكومي صحراوي',
                'license_number' => 'VALL004',
                'type' => 'governmental',
                'address' => 'شارع الخضرة، موط',
                'phone' => '0927890123',
                'hotline' => '122',
                'email' => 'mut@mohp.gov.eg',
                'website' => null,
                'longitude' => 28.9833,
                'latitude' => 25.4833,
                'region_id' => 59
            ],
            [
                'id' => 125,
                'name' => 'مستشفى الفرافرة العام',
                'description' => 'مستشفى حكومي واحة',
                'license_number' => 'VALL005',
                'type' => 'governmental',
                'address' => 'شارع الواحة، الفرافرة',
                'phone' => '0928901234',
                'hotline' => '122',
                'email' => 'farafra@mohp.gov.eg',
                'website' => null,
                'longitude' => 27.0500,
                'latitude' => 27.0667,
                'region_id' => 59
            ],

            // مستشفيات مطروح
            [
                'id' => 126,
                'name' => 'مستشفى الحمام العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'MATR003',
                'type' => 'governmental',
                'address' => 'شارع البحر، الحمام',
                'phone' => '0467890123',
                'hotline' => '122',
                'email' => 'hammam@mohp.gov.eg',
                'website' => null,
                'longitude' => 28.9500,
                'latitude' => 31.3500,
                'region_id' => 60
            ],
            [
                'id' => 127,
                'name' => 'مستشفى الضبعة العام',
                'description' => 'مستشفى حكومي نووي',
                'license_number' => 'MATR004',
                'type' => 'governmental',
                'address' => 'شارع المفاعل، الضبعة',
                'phone' => '0468901234',
                'hotline' => '122',
                'email' => 'dabaa@mohp.gov.eg',
                'website' => null,
                'longitude' => 28.7500,
                'latitude' => 31.0833,
                'region_id' => 60
            ],
            [
                'id' => 128,
                'name' => 'مستشفى سيدي براني العام',
                'description' => 'مستشفى حكومي حدودي',
                'license_number' => 'MATR005',
                'type' => 'governmental',
                'address' => 'شارع الحدود، سيدي براني',
                'phone' => '0469012345',
                'hotline' => '122',
                'email' => 'sidibarani@mohp.gov.eg',
                'website' => null,
                'longitude' => 26.0000,
                'latitude' => 31.6000,
                'region_id' => 60
            ],

            // مستشفيات شمال سيناء
            [
                'id' => 129,
                'name' => 'مستشفى الشيخ زويد العام',
                'description' => 'مستشفى حكومي حدودي',
                'license_number' => 'NSIN003',
                'type' => 'governmental',
                'address' => 'شارع التحرير، الشيخ زويد',
                'phone' => '0685678901',
                'hotline' => '122',
                'email' => 'sheikhzuweid@mohp.gov.eg',
                'website' => null,
                'longitude' => 34.2000,
                'latitude' => 31.1167,
                'region_id' => 61
            ],
            [
                'id' => 130,
                'name' => 'مستشفى رفح العام',
                'description' => 'مستشفى حكومي حدودي',
                'license_number' => 'NSIN004',
                'type' => 'governmental',
                'address' => 'شارع فلسطين، رفح',
                'phone' => '0686789012',
                'hotline' => '122',
                'email' => 'rafah@mohp.gov.eg',
                'website' => null,
                'longitude' => 34.2500,
                'latitude' => 31.2833,
                'region_id' => 61
            ],
            [
                'id' => 131,
                'name' => 'مستشفى بير العبد العام',
                'description' => 'مستشفى حكومي صحراوي',
                'license_number' => 'NSIN005',
                'type' => 'governmental',
                'address' => 'شارع الصحراء، بير العبد',
                'phone' => '0687890123',
                'hotline' => '122',
                'email' => 'biralabд@mohp.gov.eg',
                'website' => null,
                'longitude' => 33.8000,
                'latitude' => 30.9000,
                'region_id' => 61
            ],

            // مستشفيات جنوب سيناء
            [
                'id' => 132,
                'name' => 'مستشفى نويبع السياحي',
                'description' => 'مستشفى حكومي سياحي',
                'license_number' => 'SSIN003',
                'type' => 'governmental',
                'address' => 'شارع البحر، نويبع',
                'phone' => '0697890123',
                'hotline' => '122',
                'email' => 'nuweiba@mohp.gov.eg',
                'website' => null,
                'longitude' => 34.6667,
                'latitude' => 29.0333,
                'region_id' => 61
            ],
            [
                'id' => 133,
                'name' => 'مستشفى سانت كاترين',
                'description' => 'مستشفى حكومي ديني',
                'license_number' => 'SSIN004',
                'type' => 'governmental',
                'address' => 'شارة الدير، سانت كاترين',
                'phone' => '0698901234',
                'hotline' => '122',
                'email' => 'saintkaterine@mohp.gov.eg',
                'website' => null,
                'longitude' => 33.9500,
                'latitude' => 28.5500,
                'region_id' => 61
            ],
            [
                'id' => 134,
                'name' => 'مستشفى رأس سدر العام',
                'description' => 'مستشفى حكومي ساحلي',
                'license_number' => 'SSIN005',
                'type' => 'governmental',
                'address' => 'شارع خليج السويس، رأس سدر',
                'phone' => '0699012345',
                'hotline' => '122',
                'email' => 'rassedr@mohp.gov.eg',
                'website' => null,
                'longitude' => 32.7000,
                'latitude' => 29.6167,
                'region_id' => 61
            ],

            // مستشفيات سوهاج
            [
                'id' => 135,
                'name' => 'مستشفى طهطا العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'SOHA003',
                'type' => 'governmental',
                'address' => 'شارع الأثار، طهطا',
                'phone' => '0937890123',
                'hotline' => '122',
                'email' => 'tahta@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.5000,
                'latitude' => 26.7667,
                'region_id' => 61
            ],
            [
                'id' => 136,
                'name' => 'مستشفى المراغة العام',
                'description' => 'مستشفى حكومي محلي',
                'license_number' => 'SOHA004',
                'type' => 'governmental',
                'address' => 'شارع النيل، المراغة',
                'phone' => '0938901234',
                'hotline' => '122',
                'email' => 'maragha@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.6333,
                'latitude' => 26.3833,
                'region_id' => 61
            ],
            [
                'id' => 137,
                'name' => 'مستشفى أخميم العام',
                'description' => 'مستشفى حكومي أثري',
                'license_number' => 'SOHA005',
                'type' => 'governmental',
                'address' => 'شارع الفراعنة، أخميم',
                'phone' => '0939012345',
                'hotline' => '122',
                'email' => 'akhmim@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.7500,
                'latitude' => 26.0667,
                'region_id' => 61
            ],

            // مستشفيات جامعية وتخصصية إضافية
            [
                'id' => 138,
                'name' => 'مستشفى القصر العيني الجديد',
                'description' => 'مستشفى جامعي متطور',
                'license_number' => 'CAIRO029',
                'type' => 'university',
                'address' => 'شارع القصر العيني، المنيل',
                'phone' => '0223651500',
                'hotline' => '16500',
                'email' => 'newkasr@kasralainy.edu.eg',
                'website' => 'www.kasralainy.edu.eg',
                'longitude' => 31.2298,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 139,
                'name' => 'المعهد القومي للأورام',
                'description' => 'معهد متخصص في علاج الأورام',
                'license_number' => 'ONCO001',
                'type' => 'governmental',
                'address' => 'شارع فم الخليج، القاهرة',
                'phone' => '0223642750',
                'hotline' => '16600',
                'email' => 'nci@nci.cu.edu.eg',
                'website' => 'www.nci.cu.edu.eg',
                'longitude' => 31.2298,
                'latitude' => 30.0296,
                'region_id' => 1
            ],
            [
                'id' => 140,
                'name' => 'مستشفى أحمد ماهر التعليمي',
                'description' => 'مستشفى تعليمي متخصص',
                'license_number' => 'CAIRO030',
                'type' => 'governmental',
                'address' => 'شارع أحمد ماهر، العباسية',
                'phone' => '0224831000',
                'hotline' => '16700',
                'email' => 'ahmedmaher@mohp.gov.eg',
                'website' => null,
                'longitude' => 31.2854,
                'latitude' => 30.0734,
                'region_id' => 10
            ],

            // مستشفيات خاصة متطورة
            [
                'id' => 141,
                'name' => 'مستشفى مغربي للعيون',
                'description' => 'مستشفى خاص متخصص في العيون',
                'license_number' => 'PRIV001',
                'type' => 'private',
                'address' => 'شارع النزهة، مصر الجديدة',
                'phone' => '0224171500',
                'hotline' => '19400',
                'email' => 'info@maghrabi.com.eg',
                'website' => 'www.maghrabi.com.eg',
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],
            [
                'id' => 142,
                'name' => 'مستشفى النيل بدراوي',
                'description' => 'مستشفى خاص راقي',
                'license_number' => 'PRIV002',
                'type' => 'private',
                'address' => 'كورنيش النيل، المعادي',
                'phone' => '0225261500',
                'hotline' => '19500',
                'email' => 'info@nilebadrawi.com',
                'website' => 'www.nilebadrawi.com',
                'longitude' => 31.2622,
                'latitude' => 29.9601,
                'region_id' => 4
            ],
            [
                'id' => 143,
                'name' => 'مركز القلب الأوروبي',
                'description' => 'مركز متخصص في جراحة القلب',
                'license_number' => 'PRIV003',
                'type' => 'private',
                'address' => 'شارع الثورة، مصر الجديدة',
                'phone' => '0224172000',
                'hotline' => '19600',
                'email' => 'info@europeanheart.com.eg',
                'website' => 'www.europeanheart.com.eg',
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],
            [
                'id' => 144,
                'name' => 'مستشفى الجزيرة',
                'description' => 'مستشفى خاص متعدد التخصصات',
                'license_number' => 'PRIV004',
                'type' => 'private',
                'address' => 'شارع الجزيرة، الزمالك',
                'phone' => '0227361000',
                'hotline' => '19700',
                'email' => 'info@aljazeera-hospital.com',
                'website' => 'www.aljazeera-hospital.com',
                'longitude' => 31.2245,
                'latitude' => 30.0626,
                'region_id' => 1
            ],
            [
                'id' => 145,
                'name' => 'مستشفى الشفاء الخاص',
                'description' => 'مستشفى خاص في الإسكندرية',
                'license_number' => 'ALEX012',
                'type' => 'private',
                'address' => 'شارع سعد زغلول، الإسكندرية',
                'phone' => '0334566000',
                'hotline' => '19800',
                'email' => 'info@shifa-alex.com',
                'website' => 'www.shifa-alex.com',
                'longitude' => 29.9097,
                'latitude' => 31.2001,
                'region_id' => 17
            ],

            // مستشفيات خيرية ومؤسسات اجتماعية
            [
                'id' => 146,
                'name' => 'مستشفى مجدي يعقوب للقلب',
                'description' => 'مستشفى خيري للقلب',
                'license_number' => 'CHAR001',
                'type' => 'charity',
                'address' => 'القاهرة الجديدة',
                'phone' => '0226177500',
                'hotline' => '19900',
                'email' => 'info@myf.org.eg',
                'website' => 'www.myf.org.eg',
                'longitude' => 31.4292,
                'latitude' => 30.0131,
                'region_id' => 7
            ],
            [
                'id' => 147,
                'name' => 'مستشفى 57357',
                'description' => 'مستشفى خيري لسرطان الأطفال',
                'license_number' => 'CHAR002',
                'type' => 'charity',
                'address' => 'شارع المنيل، القاهرة',
                'phone' => '0219057357',
                'hotline' => '57357',
                'email' => 'info@57357.org',
                'website' => 'www.57357.org',
                'longitude' => 31.2298,
                'latitude' => 30.0150,
                'region_id' => 1
            ],
            [
                'id' => 148,
                'name' => 'مستشفى بهية لعلاج السرطان',
                'description' => 'مستشفى خيري لسرطان النساء',
                'license_number' => 'CHAR003',
                'type' => 'charity',
                'address' => 'الحي المتميز، 6 أكتوبر',
                'phone' => '01025757575',
                'hotline' => '19191',
                'email' => 'info@baheyaeg.org',
                'website' => 'www.baheyaeg.org',
                'longitude' => 31.0167,
                'latitude' => 29.9167,
                'region_id' => 14
            ],
            [
                'id' => 149,
                'name' => 'مستشفى أطفال مصر الخيري',
                'description' => 'مستشفى خيري للأطفال',
                'license_number' => 'CHAR004',
                'type' => 'charity',
                'address' => 'شارع المرج، مصر الجديدة',
                'phone' => '0224171800',
                'hotline' => '16800',
                'email' => 'info@childrenofegypt.org',
                'website' => 'www.childrenofegypt.org',
                'longitude' => 31.3260,
                'latitude' => 30.0885,
                'region_id' => 3
            ],
            [
                'id' => 150,
                'name' => 'مستشفى الناس الخيري',
                'description' => 'مستشفى خيري شعبي',
                'license_number' => 'CHAR005',
                'type' => 'charity',
                'address' => 'حي السلام، القاهرة',
                'phone' => '0224566789',
                'hotline' => '15500',
                'email' => 'info@alnas-charity.org',
                'website' => 'www.alnas-charity.org',
                'longitude' => 31.3500,
                'latitude' => 30.1500,
                'region_id' => 10
            ]
        ];

        DB::table('hospitals')->insert($hospitals);
    }
}
